name: leo_find_it_new
description: A BLE tracker scanner
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  cupertino_icons: ^1.0.2
  sensors_plus: ^5.0.0
  intl: ^0.18.1
  google_fonts: ^6.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/leo_splash.png
    - assets/LeoPhoto.jpg

  fonts:

    # (branding / headers)

    - family: Inter
      fonts:
        - asset: assets/Inter/static/Inter_18pt-Regular.ttf
        - asset: assets/Inter/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/Inter/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/Inter/static/Inter_18pt-Bold.ttf
          weight: 700


    # (body / buttons)

    - family: Montserrat
      fonts:
        - asset: assets/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/Montserrat/static/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/Montserrat/static/Montserrat-Bold.ttf
          weight: 700